[package]
name = "kraken-async-rs"
version = "0.0.2"
edition = "2021"
authors = ["Brendan Blanchard"]
description = "An async REST and WSS client for the Kraken Pro APIs"
license = "MIT"
repository = "https://github.com/Brendan-Blanchard/kraken-async-rs"
keywords = ["tokio", "async", "kraken", "trading", "crypto"]
categories = ["asynchronous", "finance", "api-bindings"]
exclude = [".idea", ".gitignore", ".github", ".env"]

[dependencies]
base64 = "0.22.0"
hmac = "0.12.1"
hyper = { version = "1.3.1", features = ["full"] }
hyper-util = { version = "0.1.3", features = ["full", "client-legacy", "tokio"] }
http-body-util = "0.1.1"
hyper-tls = "0.6.0"
sha2 = "0.10.8"
tokio = { version = "1.37.0", features = ["full"] }
dotenvy = "0.15.7"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = { version = "1.0.116", features = [] }
url = "2.5.0"
serde_with = { version = "3.7.0", features = ["time_0_3"] }
serde_tuple = "0.5.0"
tracing = "0.1.40"
secrecy = "0.8.0"
async-rate-limit = "0.0.4"
simple-builder = "0.0.2"
to-query-params = "0.0.4"
tokio-tungstenite = { version = "0.21.0", features = ["native-tls"] }
futures-util = "0.3.29"
tokio-stream = "0.1.14"
serde-this-or-that = "0.4.2"
time = { version = "0.3.36", features = ["serde", "macros", "parsing"] }
rust_decimal = { version = "1.35.0", features = ["serde-with-str"] }
rust_decimal_macros = "1.34.2"

[dev-dependencies]
wiremock = "0.6.0"
tracing-subscriber = "0.3.17"
ws-mock = "0.0.1"
